config/routes.rb
Rasberry::Application.routes.draw do

  resources :perfectionist_badges, :controller => 'badges'
  resources :my_first_semester_badges, :controller => 'badges'
  resources :ten_thousand_lines_of_codes, :controller => 'badges'
  resources :five_thousand_lines_of_codes, :controller => 'badges'
  resources :one_thousand_lines_of_codes, :controller => 'badges'
  resources :the_good_student_badges, :controller => 'badges'
  resources :the_rookie_badges, :controller => 'badges'
  resources :badges

  resources :courses
  resources :notifications
  resources :stats_sheets
  resources :grade_sheets
  resources :exercises
  resources :lessons
  resources :users
  resources :user_sessions

  resource :account, :controller => 'users'

  match "about" => "static#about", :as => :about
  match "terms" => "static#terms", :as => :terms
  match "privacy" => "static#privacy", :as => :privacy

  match "login" => "user_sessions#new", :as=>:login
  match "logout" => "user_sessions#destroy", :as=>:logout
  match "register" => "users#new", :as => :register

  match "stats_sheet"=>"stats_sheets#show", :id=>"me", :as=>:stats_sheet
    
  match "code/start/:id"=>"code#start", :as=>:start_coding, :via=>:post
  match "code"=>"code#show", :as=>:code, :via=>:get
  match "code/quit"=>"code#quit", :as=>:quit_coding, :via=>:post
  match "code/action"=>"code#do_action", :as=>:do_action, :via=>:post
  match "code/grade"=>"code#grade", :as=>:get_grade, :via=>:get
  match "code/already_doing_exercise"=>"code#already_doing_exercise", :as=>:choose_code, :via=>:get

  root :to => "static#index", :as=>:home

end

app/models/user.rb
class User < ActiveRecord::Base

  has_one :code_session, :dependent=>:destroy
  has_one :stats_sheet, :as=>:xp, :dependent=>:destroy
  after_initialize lambda {|u| u.stats_sheet = StatsSheet.new unless stats_sheet} 

  has_and_belongs_to_many :earned_badges, :class_name=>"Badge", :order=>"created_at DESC"

  validates :stats_sheet, :presence=>true
  
  # Get the top 10 users by XP (for leaderboard)
  scope :leaders, where(:anonymous => false).limit(10).includes("stats_sheet").order("stats_sheets.total_xp")
  
  # Used to make random strings
  @@CHAR_TAB = ("A".."Z").to_a + ("a".."z").to_a + (1..9).to_a + %w{ _ -}

  acts_as_authentic do |c|
    # for available options see documentation in: Authlogic::ActsAsAuthentic
    # c.my_config_option = my_value 
  end 

  attr_accessible :username, :email, :password, :password_confirmation

  # The user is going to start coding this exercise.
  # Creates a new code session.
  def start_coding(exercise)
    unless code_session
      self.code_session = CodeSession.new(:exercise=>exercise)
    end
  end

  # The has finished the exercise. 
  # Destroys the current code session. Does
  # nothing if the user doesn't have a code session.
  def end_code_session
    if code_session
      code_session.destroy
      self.code_session = nil
    end
  end

  # Returns the exercise the user is currently doing.
  def current_exercise
    if code_session
      code_session.exercise
    end
  end

  def current_lesson
    if code_session
      code_session.exercise.lesson
    end
  end

  def current_course
    if code_session
      code_session.exercise.lesson.course
    end
  end

  # Returns the number of seconds the user has
  # left to complete the exercise.
  def seconds_left_in_code_session
    if code_session 
      start_time = code_session.created_at 
      end_time = start_time + current_exercise.minutes * 60#secs/min
      elapsed_seconds = (end_time - Time.now).ceil
      elapsed_seconds >= 0 ? elapsed_seconds : 0
    end
  end

  # Create an anonymous user with a random user name
  # and a random password.
  def self.new_anonymous
    size = @@CHAR_TAB.size 
    rand_password = (0..32).map { @@CHAR_TAB[rand(size)] }.join
    rand_sufix = (0..5).map { @@CHAR_TAB[rand(size)] }.join
    User.new do |u|
      u.username = "user-" + rand_sufix
      u.password = rand_password
      u.password_confirmation = rand_password
      u.email = u.username + "@example.com"
      u.anonymous = true
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :require_non_anonymous_user, :except=> [:new, :create]
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(params[:user])
    if @user.save && 
      UserSession.create(:username => @user.username, :password => @user.password)
        flash[:notice] = "You are registered! Welcome to PrepCode!"
        redirect_to home_path 
    else
      render :action => :new
    end
  end
  
  def show
    @user = current_user
  end

  def edit
    @user = current_user
  end
  
  def update
    @user = current_user # makes our views "cleaner" and more consistent
    if @user.update_attributes(params[:user])
      flash[:notice] = "Account updated!"
      redirect_to account_url
    else
      render :action => :edit
    end
  end
end

app/views/users/_form.html.erb
<%= form_for @user do |form|%>

  <% if @user.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <%end %>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password, form.object.new_record? ? nil : "Change password" %>
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>

  <%= form.submit @user.new_record? ? "Sign Up" : "Save", :class => "button green"  %>
<% end %>

app/views/users/edit.html.erb
<h2>Edit My Account</h2>

<%= render "form" %>

<br /><%= link_to "My Profile", account_path %>

app/views/users/new.html.erb
<h2 class="full">Register <small>By registering, you agree to abide by PrepCode's <a href="#">Terms and Conditions</a></small></h2>

<%= render 'form' %> 

app/views/users/show.html.erb
<p>
  <b>Username:</b>
  <%= @user.username %>
</p>

<p><%= link_to "Badges (#{badge_progress(current_user)})", badges_path, :id => "badges" %></p>

<p><%= link_to "Stats sheet", stats_sheet_path, :id => "stats" %></p>
	
<p>
  <b>Login count:</b>
  <%= @user.login_count %>
</p>

<p>
  <b>Last request at:</b>
  <%= @user.last_request_at %>
</p>

<p>
  <b>Last login at:</b>
  <%= @user.last_login_at %>
</p>

<p>
  <b>Current login at:</b>
  <%= @user.current_login_at %>
</p>

<p>
  <b>Last login ip:</b>
  <%= @user.last_login_ip %>
</p>

<p>
  <b>Current login ip:</b>
  <%= @user.current_login_ip %>
</p>

<%= link_to 'Edit', edit_account_path %>