config/routes.rb
Rasberry::Application.routes.draw do

  resources :perfectionist_badges, :controller => 'badges'
  resources :my_first_semester_badges, :controller => 'badges'
  resources :ten_thousand_lines_of_codes, :controller => 'badges'
  resources :five_thousand_lines_of_codes, :controller => 'badges'
  resources :one_thousand_lines_of_codes, :controller => 'badges'
  resources :the_good_student_badges, :controller => 'badges'
  resources :the_rookie_badges, :controller => 'badges'
  resources :badges

  resources :courses
  resources :notifications
  resources :stats_sheets
  resources :grade_sheets
  resources :exercises
  resources :lessons
  resources :users
  resources :user_sessions

  resource :account, :controller => 'users'

  match "about" => "static#about", :as => :about
  match "terms" => "static#terms", :as => :terms
  match "privacy" => "static#privacy", :as => :privacy

  match "login" => "user_sessions#new", :as=>:login
  match "logout" => "user_sessions#destroy", :as=>:logout
  match "register" => "users#new", :as => :register

  match "stats_sheet"=>"stats_sheets#show", :id=>"me", :as=>:stats_sheet
    
  match "code/start/:id"=>"code#start", :as=>:start_coding, :via=>:post
  match "code"=>"code#show", :as=>:code, :via=>:get
  match "code/quit"=>"code#quit", :as=>:quit_coding, :via=>:post
  match "code/action"=>"code#do_action", :as=>:do_action, :via=>:post
  match "code/grade"=>"code#grade", :as=>:get_grade, :via=>:get
  match "code/already_doing_exercise"=>"code#already_doing_exercise", :as=>:choose_code, :via=>:get

  root :to => "static#index", :as=>:home

end

app/models/lesson.rb
class Lesson < ActiveRecord::Base

  validates :title, :presence=>true

  has_many :exercises
  belongs_to :course

  scope :finished, lambda{ where(:finished => true) }

  def to_s
    "#{id}-#{title.gsub(/[^a-z0-9]+/i, '-').downcase}"
  end
  
  def to_param
    to_s
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController

  before_filter :require_admin, :except=>[:index, :show]

  # GET /lessons
  # GET /lessons.xml
  def index
    if current_user.admin?
      @lessons = Lesson.all
    else
      @lessons = Lesson.finished
    end

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @lessons }
    end
  end

  # GET /lessons/1
  # GET /lessons/1.xml
  def show
    @lesson = Lesson.find(params[:id])
    if not @lesson.finished? and not current_user.admin?
      redirect_to home_url
      return
    end

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @lesson }
    end
  end

  # GET /lessons/new
  # GET /lessons/new.xml
  def new
    @lesson = Lesson.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @lesson }
    end
  end

  # GET /lessons/1/edit
  def edit
    @lesson = Lesson.find(params[:id])
  end

  # POST /lessons
  # POST /lessons.xml
  def create
    @lesson = Lesson.new(params[:lesson])

    respond_to do |format|
      if @lesson.save
        format.html { redirect_to(@lesson, :notice => 'Lesson was successfully created.') }
        format.xml  { render :xml => @lesson, :status => :created, :location => @lesson }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @lesson.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /lessons/1
  # PUT /lessons/1.xml
  def update
    @lesson = Lesson.find(params[:id])

    respond_to do |format|
      if @lesson.update_attributes(params[:lesson])
        format.html { redirect_to(@lesson, :notice => 'Lesson was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @lesson.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /lessons/1
  # DELETE /lessons/1.xml
  def destroy
    @lesson = Lesson.find(params[:id])
    @lesson.destroy

    respond_to do |format|
      format.html { redirect_to(lessons_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/views/lessons/_form.html.erb
<%= form_for(@lesson) do |f| %>
  <% if @lesson.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lesson.errors.count, "error") %> prohibited this lesson from being saved:</h2>

      <ul>
      <% @lesson.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :image_url%><br />
    <%= f.text_field :image_url %>
  </div>

  <div class="field">
    <%= f.label :course_id%>
    <%= f.collection_select :course_id, Course.all, :id, :title %>
  </div>

  <div class="field">
    <%= f.label :finished %>
    <%= f.check_box :finished %>
  </div>

  <div class="field">
    <%= f.label :difficulty, "Lesson difficulty"%>
    <%= f.text_field :difficulty %>
  </div>

  <div class="field">
    <%= f.label :number, "Lesson number"%>
    <%= f.text_field :number %>
  </div>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :text %><br />
    <%= f.text_area :text %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lessons/edit.html.erb
<h2>Editing lesson</h2>

<%= render 'form' %>

<%= link_to 'Show', @lesson %> |
<%= link_to 'Back', lessons_path %>

app/views/lessons/index.html.erb
<% if flash[:notice] %>
  <p id="notice"> <%= flash[:notice] %> </p>
<% end %>

<ul id="lessons_list">
  <% @lessons.each do |lesson| %>
    <li class="lesson_list_item">
      <%= link_to(lesson.title, lesson, :class=>"heading_link") %><br>
      <small><%= link_to "Comments", lesson_path(lesson, :anchor => "disqus_thread"), "data-disqus-identifier" => lesson %></small>
      <p class="content_paragraph"><%= lesson.description%></p>

      <% if current_user and current_user.admin? %>
        <%= link_to 'Edit', edit_lesson_path(lesson), :class=>"button" %>
        <%= link_to 'Destroy', lesson, :confirm => 'Are you sure?', :method => :delete, :class=>"button" %>
        <%= link_to 'New Lesson', new_lesson_path, :class=>'button' %>
      <% end %>
    </li>
  <% end %>
</ul>

<script type="text/javascript">
    var disqus_shortname = 'prepcode';

    (function () {
        var s = document.createElement('script'); s.async = true;
        s.type = 'text/javascript';
        s.src = 'http://' + disqus_shortname + '.disqus.com/count.js';
        (document.getElementsByTagName('HEAD')[0] || document.getElementsByTagName('BODY')[0]).appendChild(s);
    }());
</script>

app/views/lessons/new.html.erb
<h2>New lesson</h2>

<%= render 'form' %>

<%= link_to 'Back', lessons_path %>

app/views/lessons/show.html.erb
<p id="notice"><%= notice %></p>

<ul id="lesson_exercises">
  <%= render :partial=>'exercises/exercise_li', 
      :collection=>@lesson.exercises %>
</ul>

<h2>
  <%= @lesson.title %>
</h2>

<p>
  <%= raw @lesson.text %>
</p>

<div id="disqus_thread"></div>
<script>
  var disqus_shortname = 'precode'; 
  var disqus_identifier = '<%= @lesson.to_param %>';
</script>
<script src="http://prepcode.disqus.com/embed.js"></script>

<% if current_user.admin? %>
  <%= link_to 'Edit', edit_lesson_path(@lesson), :class => 'button' %>
<% end %>