config/routes.rb
Rasberry::Application.routes.draw do

  resources :perfectionist_badges, :controller => 'badges'
  resources :my_first_semester_badges, :controller => 'badges'
  resources :ten_thousand_lines_of_codes, :controller => 'badges'
  resources :five_thousand_lines_of_codes, :controller => 'badges'
  resources :one_thousand_lines_of_codes, :controller => 'badges'
  resources :the_good_student_badges, :controller => 'badges'
  resources :the_rookie_badges, :controller => 'badges'
  resources :badges

  resources :courses
  resources :notifications
  resources :stats_sheets
  resources :grade_sheets
  resources :exercises
  resources :lessons
  resources :users
  resources :user_sessions

  resource :account, :controller => 'users'

  match "about" => "static#about", :as => :about
  match "terms" => "static#terms", :as => :terms
  match "privacy" => "static#privacy", :as => :privacy

  match "login" => "user_sessions#new", :as=>:login
  match "logout" => "user_sessions#destroy", :as=>:logout
  match "register" => "users#new", :as => :register

  match "stats_sheet"=>"stats_sheets#show", :id=>"me", :as=>:stats_sheet
    
  match "code/start/:id"=>"code#start", :as=>:start_coding, :via=>:post
  match "code"=>"code#show", :as=>:code, :via=>:get
  match "code/quit"=>"code#quit", :as=>:quit_coding, :via=>:post
  match "code/action"=>"code#do_action", :as=>:do_action, :via=>:post
  match "code/grade"=>"code#grade", :as=>:get_grade, :via=>:get
  match "code/already_doing_exercise"=>"code#already_doing_exercise", :as=>:choose_code, :via=>:get

  root :to => "static#index", :as=>:home

end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController

  before_filter :require_admin, :except => [:index, :show]

  # GET /exercises
  # GET /exercises.xml
  def index
    if current_user.admin?
      @exercises = Exercise.all
    else
      @exercises = Exercise.finished 
    end

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @exercises }
    end
  end

  # GET /exercises/1
  # GET /exercises/1.xml
  def show
    @exercise = Exercise.find(params[:id])
    if not @exercise.finished and not current_user.admin?
      redirect_to home_url
      return
    end

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @exercise }
    end
  end

  # GET /exercises/new
  # GET /exercises/new.xml
  def new
    @exercise = Exercise.new
    @exercise.hints.build
    @exercise.unit_test = UnitTest.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @exercise }
    end
  end

  # GET /exercises/1/edit
  def edit
    @exercise = Exercise.find(params[:id])
  end

  # POST /exercises
  # POST /exercises.xml
  def create
    @exercise = Exercise.new(params[:exercise])

    respond_to do |format|
      if @exercise.save
        format.html { redirect_to(@exercise, :notice => 'Exercise was successfully created.') }
        format.xml  { render :xml => @exercise, :status => :created, :location => @exercise }
      else
        @exercise.unit_test = UnitTest.new
        format.html { render :action => "new" }
        format.xml  { render :xml => @exercise.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /exercises/1
  # PUT /exercises/1.xml
  def update
    @exercise = Exercise.find(params[:id])

    respond_to do |format|
      if @exercise.update_attributes(params[:exercise])
        format.html { redirect_to(@exercise, :notice => 'Exercise was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @exercise.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /exercises/1
  # DELETE /exercises/1.xml
  def destroy
    @exercise = Exercise.find(params[:id])
    @exercise.destroy

    respond_to do |format|
      format.html { redirect_to(exercises_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/exercises_helper.rb
module ExercisesHelper

  def grade_for(user, opts)
    unless user.anonymous?
      exercise = opts[:on]
      grades = GradeSheet.grades_for(user) 
      return grades[exercise.id] || ""         
    end
    ""
  end
end

app/views/exercises/_exercise.html.erb
<div class="row sixteen columns">
  <h3><%= exercise.title %></h3>
  <p>
    <%= exercise.description %>
  </p>
  <%= button_to 'Start Exercise', start_coding_path(exercise),  :class => "button", :method=>:post%>
  <% if current_user.admin? %>
    <%= link_to 'Show', exercise, :class => "button" %>
    <%= link_to 'Edit', edit_exercise_path(exercise), :class => "button" %>
    <%= link_to 'Destroy', exercise, :confirm => 'Are you sure?', :method => :delete, :class => "button" %>
  <% end %>
</div>

app/views/exercises/_exercise_li.html.erb
<li class="exercise-li">
  <span class="exercise-li-title"><%= exercise_li.title %></span> 
  <span class="exercise-li-grade"><%= grade_for(current_user, :on => exercise_li) %></span>
  <%= button_to("Start Exercise",
                start_coding_path(exercise_li),
                :class=>"button",
                :method=>:post) %>
  <p>
    <%= exercise_li.description %>
  </p>
</li>

app/views/exercises/_form.html.erb
<%= form_for(@exercise, :html=>{:multipart=>true}) do |f| %>
  <% if @exercise.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@exercise.errors.count, "error") %> prohibited this exercise from being saved:</h2>

      <ul>
      <% @exercise.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :lesson_id %>
    <%= f.collection_select :lesson_id, Lesson.all, :id, :title %>
  </div>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :finished %>
    <%= f.check_box :finished %>
  </div>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description, :rows=>8, :cols=>80 %>
  </div>

  <%= render 'stats_sheet', :f => f%>

  <%= render 'unit_test', :f => f %>

  <div class="field">
    <%= f.label :minutes %><br />
    <%= f.text_field :minutes %>
  </div>
  
  <div class="field">
    <%= f.label :text %><br />
    <%= f.text_area :text, :cols=>80%>
  </div>

  <div class="field">
    <%= f.label :tutorial %><br />
    <%= f.text_area :tutorial, :cols=>80%>
  </div>

  <%= render 'hint', :f => f %> 

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/exercises/_hint.html.erb
<%= f.fields_for :hints do |builder| %>
  <%= builder.label :text, "Hint Text" %><br/>
  <%= builder.text_area :text, :cols=>80 %>
<% end %> 

app/views/exercises/_stats_sheet.html.erb
<%= f.fields_for :stats_sheet do |builder|%>

  <div class="field">
    <%= builder.label :searching_xp %>
    <%= builder.text_field :searching_xp %>
  </div>

  <div class="field">
    <%= builder.label :sorting_xp %>
    <%= builder.text_field :sorting_xp %>
  </div>

  <div class="field">
    <%= builder.label :numeric_xp %>
    <%= builder.text_field :numeric_xp %>
  </div>

  <div class="field">
    <%= builder.label :linked_list_xp%>
    <%= builder.text_field :linked_list_xp %>
  </div>

  <div class="field">
    <%= builder.label :hash_xp%>
    <%= builder.text_field :hash_xp %>
  </div>

  <div class="field">
    <%= builder.label :array_xp %>
    <%= builder.text_field :array_xp %>
  </div>
<% end %>

app/views/exercises/_unit_test.html.erb
<div class="field">
  <% if @exercise.unit_test.new_record? %>
    <%= f.fields_for :unit_test do |builder| %>
      <%= builder.label :uploaded_unit_test, "Upload Unit Test"%><br />
      <%= builder.file_field :uploaded_unit_test %>
    <% end %>
  <% else %>
    <%= f.fields_for :unit_test do |builder| %>
      <%= builder.label :src_code, "Unit Test" %><br/>
      <%= builder.text_area :src_code, :cols=>80%>
    <% end %>
<% end%>
</div>

app/views/exercises/edit.html.erb
<h2>Editing exercise</h2>

<%= render 'form' %>

<%= link_to 'Show', @exercise %> |
<%= link_to 'Back', exercises_path %>

app/views/exercises/index.html.erb
<h2>Exercises</h2>

<div id="exercises">
  <%= render :partial=>'exercise', :collection => @exercises %>
</div>

<% if current_user.admin? %>
	<div class='clear'></div>
	<%= link_to 'New Exercise', new_exercise_path, :class => "button" %>
<% end %>

app/views/exercises/new.html.erb
<h2>New exercise</h2>

<%= render 'form' %>

<%= link_to 'Back', exercises_path %>

app/views/exercises/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @exercise.title %>
</p>

<p>
  <b>Description:</b>
  <%= @exercise.description %>
</p>

<p>
  <b>Text:</b>
  <%= @exercise.text %>
</p>

<p>
  <b>Tutorial:</b>
  <%= @exercise.tutorial %>
</p>

<p>
  <b>Minutes:</b>
  <%= @exercise.minutes %>
</p>

<% if current_user.admin? %>
	<%= link_to 'Edit', edit_exercise_path(@exercise), :class => "button" %>
<% end %>
<%= link_to 'Back', exercises_path, :class => "button" %>