config/routes.rb
Rasberry::Application.routes.draw do

  resources :perfectionist_badges, :controller => 'badges'
  resources :my_first_semester_badges, :controller => 'badges'
  resources :ten_thousand_lines_of_codes, :controller => 'badges'
  resources :five_thousand_lines_of_codes, :controller => 'badges'
  resources :one_thousand_lines_of_codes, :controller => 'badges'
  resources :the_good_student_badges, :controller => 'badges'
  resources :the_rookie_badges, :controller => 'badges'
  resources :badges

  resources :courses
  resources :notifications
  resources :stats_sheets
  resources :grade_sheets
  resources :exercises
  resources :lessons
  resources :users
  resources :user_sessions

  resource :account, :controller => 'users'

  match "about" => "static#about", :as => :about
  match "terms" => "static#terms", :as => :terms
  match "privacy" => "static#privacy", :as => :privacy

  match "login" => "user_sessions#new", :as=>:login
  match "logout" => "user_sessions#destroy", :as=>:logout
  match "register" => "users#new", :as => :register

  match "stats_sheet"=>"stats_sheets#show", :id=>"me", :as=>:stats_sheet
    
  match "code/start/:id"=>"code#start", :as=>:start_coding, :via=>:post
  match "code"=>"code#show", :as=>:code, :via=>:get
  match "code/quit"=>"code#quit", :as=>:quit_coding, :via=>:post
  match "code/action"=>"code#do_action", :as=>:do_action, :via=>:post
  match "code/grade"=>"code#grade", :as=>:get_grade, :via=>:get
  match "code/already_doing_exercise"=>"code#already_doing_exercise", :as=>:choose_code, :via=>:get

  root :to => "static#index", :as=>:home

end

app/models/stats_sheet.rb
# Two models make use of the stats sheet. The user model
# and the exercise model.
#
# A user's stats sheet keeps track of the experience
# points they've earned for completing exercises.
# 
# An exercise's stats sheet describes what xp
# the user will earn after completing the exercise. 

class StatsSheet < ActiveRecord::Base

  belongs_to :xp, :polymorphic=>true

  def update_with(grade_sheet)
    update_shared_xp_fields(grade_sheet)
    update_loc_count(grade_sheet.src_code)
    calc_total_xp
    self.save!
  end

  # Returns the fields ending in _xp. For example:
  #
  #     searching_xp
  #     sorting_xp
  #     numeric_xp
  #     ...
  #
  # It does not return the total_xp field.
  def get_shared_xp_fields
    StatsSheet.shared_xp_fields
  end

  def self.shared_xp_fields
    StatsSheet.column_names.select{|m| m=~ /_xp$/}.reject{|m| m=~/total_xp/}
  end

  def self.usage_count_fields
    StatsSheet.column_names.select{|m| m=~/_count$/}
  end

  private 

  # Update this stats sheet with the xp points
  # the user earned on the grade sheet.
  def update_shared_xp_fields(grade_sheet)
    StatsSheet.shared_xp_fields.each do |m|
      current_xp = self.send(m)
      updated_xp = current_xp + grade_sheet.exercise_stats_sheet.send(m)
      self[m] += updated_xp
    end
  end

  # Update the lines of code this user has typed.
  def update_loc_count(src_code)
    if src_code
      self.loc_count = src_code.each_line.reject{|l| l.blank?}.count
    end
  end

  # Tally up all the xp fields and
  # update the total_xp field.
  def calc_total_xp
    total = 0
    get_shared_xp_fields.each do |m|
      total += send(m) 
    end
    self.total_xp = total

    self.level = XPModel.level(total_xp)
    self.xp_to_next_level = XPModel.xp_to_next(total_xp)
  end
end

app/controllers/stats_sheets_controller.rb
class StatsSheetsController < ApplicationController

  before_filter :require_non_anonymous_user
  before_filter :require_admin, :except=>[:index, :show]
  
  # GET /stats_sheets
  # GET /stats_sheets.xml
  def index
    @stats_sheets = StatsSheet.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @stats_sheets }
    end
  end

  # GET /stats_sheets/1
  # GET /stats_sheets/1.xml
  def show
    @stats_sheet = params[:id] == "me" ? current_user.stats_sheet : StatsSheet.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @stats_sheet }
    end
  end

  # GET /stats_sheets/1/edit
  def edit
    @stats_sheet = StatsSheet.find(params[:id])
  end

  # PUT /stats_sheets/1
  # PUT /stats_sheets/1.xml
  def update
    @stats_sheet = StatsSheet.find(params[:id])

    respond_to do |format|
      if @stats_sheet.update_attributes(params[:stats_sheet])
        format.html { redirect_to(@stats_sheet, :notice => 'Stats sheet was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @stats_sheet.errors, :status => :unprocessable_entity }
      end
    end
  end
end

app/helpers/stats_sheets_helper.rb
module StatsSheetsHelper
end

app/views/stats_sheets/_form.html.erb
<%= form_for(@stats_sheet) do |f| %>
  <% if @stats_sheet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@stats_sheet.errors.count, "error") %> prohibited this stats_sheet from being saved:</h2>

      <ul>
      <% @stats_sheet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :syntax_checks_count %><br />
    <%= f.text_field :syntax_checks_count %>
  </div>
  <div class="field">
    <%= f.label :solution_checks_count %><br />
    <%= f.text_field :solution_checks_count %>
  </div>
  <div class="field">
    <%= f.label :practice_seconds_count%><br />
    <%= f.text_field :practice_seconds_count%>
  </div>
  <div class="field">
    <%= f.label :total_xp %><br />
    <%= f.text_field :total_xp %>
  </div>
  <div class="field">
    <%= f.label :sorting_xp %><br />
    <%= f.text_field :sorting_xp %>
  </div>
  <div class="field">
    <%= f.label :searching_xp %><br />
    <%= f.text_field :searching_xp %>
  </div>
  <div class="field">
    <%= f.label :numeric_xp %><br />
    <%= f.text_field :numeric_xp %>
  </div>
  <div class="field">
    <%= f.label :hash_xp %><br />
    <%= f.text_field :hash_xp %>
  </div>
  <div class="field">
    <%= f.label :linked_list_xp %><br />
    <%= f.text_field :linked_list_xp %>
  </div>
  <div class="field">
    <%= f.label :array_xp %><br />
    <%= f.text_field :array_xp %>
  </div>
  <div class="field">
    <%= f.label :level %><br />
    <%= f.text_field :level %>
  </div>
  <div class="field">
    <%= f.label :xp_to_next_level %><br />
    <%= f.text_field :xp_to_next_level %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stats_sheets/edit.html.erb
<h2>Editing stats_sheet</h2>

<%= render 'form' %>

<%= link_to 'Show', @stats_sheet %> |
<%= link_to 'Back', stats_sheets_path %>

app/views/stats_sheets/index.html.erb
<h2>Listing stats_sheets</h2>

<table>
  <tr>
    <th>Syntax checks</th>
    <th>Solution checks</th>
    <th>Total practice seconds</th>
    <th>Total xp</th>
    <th>Sorting xp</th>
    <th>Searching xp</th>
    <th>Numeric xp</th>
    <th>Hash xp</th>
    <th>Linked list xp</th>
    <th>Array xp</th>
    <th>Level</th>
    <th>Xp to next level</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @stats_sheets.each do |stats_sheet| %>
  <tr>
    <td><%= stats_sheet.syntax_checks_count%></td>
    <td><%= stats_sheet.solution_checks_count%></td>
    <td><%= stats_sheet.practice_seconds_count%></td>
    <td><%= stats_sheet.total_xp %></td>
    <td><%= stats_sheet.sorting_xp %></td>
    <td><%= stats_sheet.searching_xp %></td>
    <td><%= stats_sheet.numeric_xp %></td>
    <td><%= stats_sheet.hash_xp %></td>
    <td><%= stats_sheet.linked_list_xp %></td>
    <td><%= stats_sheet.array_xp %></td>
    <td><%= stats_sheet.level %></td>
    <td><%= stats_sheet.xp_to_next_level %></td>
    <td><%= link_to 'Show', stats_sheet %></td>
    <td><%= link_to 'Edit', edit_stats_sheet_path(stats_sheet) %></td>
    <td><%= link_to 'Destroy', stats_sheet, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Stats sheet', new_stats_sheet_path %>

app/views/stats_sheets/new.html.erb
<h2>New stats_sheet</h2>

<%= render 'form' %>

<%= link_to 'Back', stats_sheets_path %>

app/views/stats_sheets/show.html.erb
<p id="notice"><%= notice %></p>

<div id="stats-sheet">

  <p class="usage-statistic">
    <b>Syntax checks:</b>
    <%= @stats_sheet.syntax_checks_count%>
  </p>

  <p class="usage-statistic">
    <b>Lines of code written:</b>
    <%= @stats_sheet.loc_count%>
  </p>

  <p class="usage-statistic">
    <b>Solution checks:</b>
    <%= @stats_sheet.solution_checks_count %>
  </p>

  <p class="usage-statistic">
    <b>Total practice seconds:</b>
    <%= @stats_sheet.practice_seconds_count%>
  </p>

  <p class="xp-statistic"> 
    <b>Total xp:</b>
    <%= @stats_sheet.total_xp %>
  </p>

  <p class="xp-statistic">
    <b>Sorting xp:</b>
    <%= @stats_sheet.sorting_xp %>
  </p>

  <p class="xp-statistic">
    <b>Searching xp:</b>
    <%= @stats_sheet.searching_xp %>
  </p>

  <p class="xp-statistic">
    <b>Numeric xp:</b>
    <%= @stats_sheet.numeric_xp %>
  </p>

  <p class="xp-statistic">
    <b>Hash xp:</b>
    <%= @stats_sheet.hash_xp %>
  </p>

  <p class="xp-statistic">
    <b>Linked list xp:</b>
    <%= @stats_sheet.linked_list_xp %>
  </p>

  <p class="xp-statistic">
    <b>Array xp:</b>
    <%= @stats_sheet.array_xp %>
  </p>

  <p class="xp-statistic">
    <b>Level:</b>
    <%= @stats_sheet.level %>
  </p>

  <p class="xp-statistic">
    <b>Xp to next level:</b>
    <%= @stats_sheet.xp_to_next_level %>
  </p>

</div>

<% if current_user.admin? %>
  <%= link_to 'Edit', edit_stats_sheet_path(@stats_sheet) %> |
  <%= link_to 'Back', stats_sheets_path %>
<% end %>